// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCDpmXxPXHF89vekSht2DqWpEy3D9vaNo',
    appId: '1:872256853267:web:008054789f65a62a94b6e6',
    messagingSenderId: '872256853267',
    projectId: 'mshop-pharmacy',
    authDomain: 'mshop-pharmacy.firebaseapp.com',
    storageBucket: 'mshop-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQqCmm-I54dHbt-gK3RKI6A_unEPIaWeM',
    appId: '1:872256853267:android:7b4ad38dc3d7d17794b6e6',
    messagingSenderId: '872256853267',
    projectId: 'mshop-pharmacy',
    storageBucket: 'mshop-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0nIiM6tCXqTNj4K1Qp2KJRRQGtfuaCRs',
    appId: '1:872256853267:ios:edb59b807714436694b6e6',
    messagingSenderId: '872256853267',
    projectId: 'mshop-pharmacy',
    storageBucket: 'mshop-pharmacy.firebasestorage.app',
    iosBundleId: 'com.example.mshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0nIiM6tCXqTNj4K1Qp2KJRRQGtfuaCRs',
    appId: '1:872256853267:ios:edb59b807714436694b6e6',
    messagingSenderId: '872256853267',
    projectId: 'mshop-pharmacy',
    storageBucket: 'mshop-pharmacy.firebasestorage.app',
    iosBundleId: 'com.example.mshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCDpmXxPXHF89vekSht2DqWpEy3D9vaNo',
    appId: '1:872256853267:web:16888ecab1a7cc1994b6e6',
    messagingSenderId: '872256853267',
    projectId: 'mshop-pharmacy',
    authDomain: 'mshop-pharmacy.firebaseapp.com',
    storageBucket: 'mshop-pharmacy.firebasestorage.app',
  );
}
